# Generated by Django 4.2.7 on 2023-11-02 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Vastralaya_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 14, 1, 42, 900537, tzinfo=datetime.timezone.utc)),
        ),
    ]
