# Generated by Django 4.2.7 on 2023-11-02 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Vastralaya_home', '0003_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 17, 7, 9, 915658, tzinfo=datetime.timezone.utc)),
        ),
    ]
